[package]
name = "rust-protobuf-journal"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[[bin]]
name = "log"
path = "src/main.rs"

[[bin]]
name = "import"
path = "src/import.rs"

[dependencies]
quick-protobuf = "0.7.0"
time = "0.2.16"
